=== ssgeejr/silo/container.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="container">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="config">
					<xs:complexType>
						<xs:sequence>

							<xs:element type="xs:string" name="application" minOccurs="1" maxOccurs="1" />
							<xs:element type="xs:boolean" name="label" minOccurs="1" maxOccurs="1" />
							
							<xs:element type="xs:string" name="application_version" minOccurs="0" nillable="true" >
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:boolean" name="fixed"  use="optional" />
											<xs:attribute type="xs:boolean" name="empty"  use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>

							<xs:element type="xs:anyURI" name="server" />

							<xs:element name="repostiory">
								<xs:complexType>
									<xs:sequence>
										<xs:extension base="xs:string">
											<xs:element type="xs:string" name="production" />
											<xs:element type="xs:string" name="snapshot" />
										</xs:extension>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="docker" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:sequence>
												<xs:element type="xs:boolean" name="clean"  minOccurs="1" maxOccurs="1"/>
												<xs:element type="xs:boolean" name="euthanize"  minOccurs="1" maxOccurs="1"/>
												<xs:element type="xs:boolean" name="push"  minOccurs="1" maxOccurs="1"/>
												<xs:element type="xs:boolean" name="tag"  minOccurs="1" maxOccurs="1"/>
												<xs:element type="xs:string" name="host"  minOccurs="1" maxOccurs="1"/>
											</xs:sequence>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>

							<xs:element name="global">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="overwrite" minOccurs="0" >
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:boolean" name="enforce" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="dir" minOccurs="0" >
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:boolean" name="enforce" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="production" minOccurs="0" >
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:boolean" name="enforce" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="purge" minOccurs="0" >
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:boolean" name="enforce" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="purge_filetype" minOccurs="0" >
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:boolean" name="enforce" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="artifacts">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="artifact" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:string" name="groupid" />
										<xs:element type="xs:string" name="artifactid" />
										<xs:element type="xs:string" name="repostiory" minOccurs="0" />
										<xs:element type="xs:anyURI" name="server" minOccurs="0" />
										<xs:element type="xs:string" name="classifier" minOccurs="0" />
										<xs:element type="xs:string" name="extension" minOccurs="0" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="dir" use="optional" />
									<xs:attribute type="xs:boolean" name="overwrite" use="optional" />
									<xs:attribute type="xs:boolean" name="production" use="optional" />
									<xs:attribute type="xs:string" name="target" use="optional" />
									<xs:attribute type="xs:boolean" name="purge" use="optional" />
									<xs:attribute type="xs:string" name="filetype" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="files">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="file" maxOccurs="unbounded"
								minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="dir" use="optional" />
											<xs:attribute type="xs:anyURI" name="source" use="optional" />
											<xs:attribute type="xs:boolean" name="overwrite" use="optional" />
											<xs:attribute type="xs:string" name="target" use="optional" />
											<xs:attribute type="xs:boolean" name="purge" use="optional" />
											<xs:attribute type="xs:string" name="filetype" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ssgeejr/silo/example/container.xml
<container xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='container.xsd'>
	<config>
		<application>test</application>
		<application_version fixed='true' empty='true'/>		
		<server>http://gee-5/artifactory</server>
		<label>true</label>
		<repostiory>
			<production>libs-release-local</production>
			<snapshot>libs-snapshot-local</snapshot>
		</repostiory>
		<docker>
			<clean>True</clean>
			<euthanize>true</euthanize>
			<push>true</push>
			<tag>true</tag>
			<host>docker.repo.gee-5</host>
		</docker>
		<global>
			<overwrite enforce='true'>true</overwrite>
			<dir enforce='false'>/tmp</dir>
			<production enforce='false'>true</production>
			<purge enforce='true'>true</purge>
			<purge_filetype enforce='false'>111</purge_filetype>
		</global>
	</config>

	<artifacts>
		<artifact dir='cache-core' overwrite='false' production='true' target='target111.jar' purge='false' filetype='111'>
			<groupid>gee-5.silo.demo</groupid>
			<artifactid>silo-artifact</artifactid>
		</artifact>
	</artifacts>
	
	<files>
		<file dir='files' overwrite='false' target='jdk.tar.gz' purge='false' filetype='222' source='http://gee-5/artifactory/remote/oracle/jdk/7u71-linux/jdk-7u71-linux-x64.tar.gz' />
	</files>
</container>
